"""initial tables

Revision ID: f09ce7f45946
Revises: 
Create Date: 2025-12-26 13:45:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = 'f09ce7f45946'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'software',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('published_date', sa.Date(), nullable=True)
    )
    op.create_table(
        'vulnerabilities',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('cve_id', sa.String(), nullable=False),
        sa.Column('software_name', sa.String(), nullable=False),
        sa.Column('affected_version', sa.String(), nullable=False),
        sa.Column('severity', sa.String(), nullable=True),
        sa.Column('patch_command', sa.String(), nullable=True),
        sa.Column('published_date', sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###

def downgrade():
    op.drop_table('vulnerabilities')
    op.drop_table('software')
